Development k3s upgrade
threefoldtech/tf-images pull request #122
Opened 2023-01-05 16:07 UTC by sameh-farouk

- fix https://github.com/threefoldtech/tf-images/issues/121
- fix `zinit` not showing k3s logs
- upgrade k3s to 1.26.0
- upgrade Zinit to v0.2.10
- pin Kubectl to v1.26.0
- rename k3s zinit service from `init` to `k3s`
- minimize container size

2023-01-18 10:15 UTC, ashraffouda commented
kubectl binary file shouldn't be here, we download it during the build

2023-01-18 10:16 UTC, ashraffouda requested changes

2023-01-18 10:16 UTC, ashraffouda commented on tfgrid3/k3s/README.md
> +https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-k3s_1.26.0-latest.flist
can we plz promote this flist?

2023-01-18 10:29 UTC, ashraffouda commented on tfgrid3/k3s/scripts/entrypoint.sh
> +    k3s agent --flannel-iface $K3S_FLANNEL_IFACE $EXTRA_ARGS 2>&1 | tee -a /var/log/k3s-service.log
is better that we stop logging to /var/log/k3s-service.log, now after your changes zinit has all logs

2023-01-24 22:30 UTC, sameh-farouk commented on tfgrid3/k3s/README.md
> +https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-k3s_1.26.0-latest.flist
will do

2023-01-25 09:32 UTC, ashraffouda approved these changes

2023-01-25 11:02 UTC, merged